# Site settings
title:          'pyo.io'
description:    'personal blog of @derekmortimer'
baseurl:        ""
url:            "https://pyo.io"

# Author
author:
  name:         Derek Mortimer
  url:          https://pyo.io
  twitter:      derekmortimer
  github:       pyoio

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
